test.pypi.org deployment (#6)
* add encrypted secrets for deployments
* apply dev (for builds from branches) or release (for Git tags) version
* specify long description format in setup.py
* remove redundand build command from CI
* add documentation and license link to README
* mention dev builds in API reference
* add pycodestyle and fix the findings

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,8 +1,35 @@
+---
 language: python
 python:
-  - "3.7"
+  - '3.7'
 install:
   - pip install -r requirements.txt -r requirements-dev.txt
 script:
   - make lint
   - make unittest
+
+before_deploy:
+  - >
+    if [[ -n "$TRAVIS_TAG" ]] && [[ "${TRAVIS_TAG}" != "$(<VERSION)" ]]; then
+        >&2 echo "ERROR: You have marked a release by applying a Git tag and your VERSION file doesn't match it"
+        >&2 echo "Tip: Don't tag if you want to deploy only to test.pypi.org"
+        false
+    fi
+  - export VERSION=${TRAVIS_TAG:-$(<VERSION).dev${TRAVIS_BUILD_NUMBER}}
+
+deploy:
+  - provider: pypi
+    user: __token__
+    password: "$TEST_PYPI_ORG_TOKEN"
+    distributions: sdist bdist_wheel
+    server: https://test.pypi.org/legacy/
+    "on":
+      all_branches: true
+      tags: false
+
+env:
+  global:
+    # TEST_PYPI_ORG_TOKEN
+    - secure: TUQef9pZbFtOBGLQkAT0pzRmYjTR6LJOucM2x+kMfGfueN1khiwx/LmcShgCha+7kH43v0/1q9Iyk6+xQIfe7TfkL5vxD90s3Ej+ioeSK0BeqaO6Tf/lnkU2AaqpJolJC+C35/whQ4d051vhUqefPN3zF0MSXrf8rYgHt59rDIwzumbJQ3+x3g+8UOwWqdhIwrt3lVWdnYaDzkIGVIys6NoUpeDLl2RvWRKT7/8SQAJ2GKS1KffzMlnk5hAP5O2RzgeB5o9n1I/hZKoS44PIPZwRzmkbl0r8wE7XRhvwgOcKxNY1lqsTpVMR2CQrNBvqeU/mBpREjsWV33s+kctl9qd/DbHVpFRGMnGbRPe8zgUNF+spr7DU5p4343KMuuuE2V9m8VGM0vI3z9ZPgVqI6dRju3M2hFMxpX2k4iVQK+mv9rvx0WkvYUEvrFE3v0D1IQ3BgOmC+cykdxeTRZPZfptNXSVQWDfO9ihKUakUyICZzO/4HrxhfUqQGcFhNmwbVj2VQW/9vFhew8CCLzfAUIzLYb+iyEsO57CHf1/5a4u3ThANUUI9LCEHQIXzhLSqdF+H3ES4LwdzTNeHxcFMShEyPs0iD71tYUXX14W6/fpI1fJukbaa1C8Af/4OKNcXS6s/88PIVQ38Jda+tp6G4BQyQAR1raTZGUMmySuvM9M=
+    # PYPI_ORG_TOKEN
+    - secure: fMpznoe0tgacFLmtNLzgDaB63enKWIfCVLHP1i4BZoywuuRMnsvZyEYmPZg7IfEF4a5q2OjscCkOcQis5k1cMHUN3dseYge+McEhPG+Lfifq3CuXyNkdi8c9JwiPTFxmBOqBDBm16edUjWVKBdLw1X7voq3Nsk9fjUWUoCTgvUSrTpcSlaUSGtGVhGOa3a/z1YynDpMVfl3knz4I3pZXoZk2OFA3zXntdFTxHOKHRpoPiasW1USDRuCmKw4Orpnu3lEFOA5MAwctLVEyFpRVy40aZrTiRWXXT++iHs+6+f+J5G8rkx7cXdi8UNa4DOKOE2236lB9SGWlsoqRSp5xHgTDobEKzsbLtjhfut4pvCaJ0zRA1Khe6CmxGQAbY0fA6Eg3WhsP285q6XdwYAG9O20++8en2rWntF9OiRfTEuXMLPY4g8y1V2hsFMROOd2a7HFPLnkG67bqU/wVNG8+xEk0dry0As9d5dtoT9dhuGy7duJE6EJjU04LwSBQajgat0wVaJouFGXWgpZUFeMJDfxI6C4BjkAvkKPX9LHiUfBIdzsbIcRSi4AP8+bQdUyfXVI86/tEVBWmtdzLBq9v2tKqVAL04/RgxoE3c5XBimD/CMoMNZRKped8h7aQtrAVGsLDv8ER7pGmiq8BsFhtAt5D4Nc+tmnpPwxDrROY+W4=
