build the package and apply dev/release version

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,13 +7,25 @@ install:
 script:
   - make lint
   - make unittest
+  - export VERSION=${TRAVIS_TAG:-$(<VERSION).dev${TRAVIS_BUILD_NUMBER}}
+  - make build VERSION=${VERSION}
+
+before_deploy:
+  - ls -al; pwd; find dist -ls
+  - >
+    if [[ -n "$TRAVIS_TAG" ]] && [[ "${TRAVIS_TAG}" != "$(<VERSION)" ]]; then
+        >&2 echo "ERROR: You have marked a release by applying a Git tag and your VERSION file doesn't match it"
+        >&2 echo "Tip: Don't tag if you want to deploy only to test.pypi.org"
+        false
+    fi
 
 deploy:
-  - provider: script
+  - provider: pypi
     user: __token__
     password: "$TEST_PYPI_ORG_TOKEN"
     distributions: sdist bdist_wheel
     server: https://test.pypi.org/legacy/
+    skip_cleanup: true
     "on":
       all_branches: true
       tags: false
